//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 该身份证已登记，请换下一位住客身份证！ 的本地化字符串。
        /// </summary>
        public static string CHANAGE_IDCARD {
            get {
                return ResourceManager.GetString("CHANAGE_IDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请核对您的入住信息！核对完成请点击下一步！ 的本地化字符串。
        /// </summary>
        public static string CHECKCHECKININFO {
            get {
                return ResourceManager.GetString("CHECKCHECKININFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入住信息上传中. . . 的本地化字符串。
        /// </summary>
        public static string CHECKININFOUPLOAD {
            get {
                return ResourceManager.GetString("CHECKININFOUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入住信息上传出错。 的本地化字符串。
        /// </summary>
        public static string CHECKININFOUPLOADERROR {
            get {
                return ResourceManager.GetString("CHECKININFOUPLOADERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入住信息上传失败。 的本地化字符串。
        /// </summary>
        public static string CHECKININFOUPLOADFAILURE {
            get {
                return ResourceManager.GetString("CHECKININFOUPLOADFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查配置文件节点是否正确！ 的本地化字符串。
        /// </summary>
        public static string CONFIG_WRONG {
            get {
                return ResourceManager.GetString("CONFIG_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备初始化中。 的本地化字符串。
        /// </summary>
        public static string DEVICEERROR {
            get {
                return ResourceManager.GetString("DEVICEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备初始化出错。 的本地化字符串。
        /// </summary>
        public static string DEVICEINITERROR {
            get {
                return ResourceManager.GetString("DEVICEINITERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在制卡。 的本地化字符串。
        /// </summary>
        public static string FABRICATIONCARD {
            get {
                return ResourceManager.GetString("FABRICATIONCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸识别模块故障！ 的本地化字符串。
        /// </summary>
        public static string FACEDETECTERROR {
            get {
                return ResourceManager.GetString("FACEDETECTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸识别模块加载失败！ 的本地化字符串。
        /// </summary>
        public static string FACEDETECTLOADERROR {
            get {
                return ResourceManager.GetString("FACEDETECTLOADERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请取走您的钞票！欢迎下次光临！ 的本地化字符串。
        /// </summary>
        public static string GETMONEY {
            get {
                return ResourceManager.GetString("GETMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请取走您的凭条！ 的本地化字符串。
        /// </summary>
        public static string GETPAPPER {
            get {
                return ResourceManager.GetString("GETPAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请取走您的房卡！ 的本地化字符串。
        /// </summary>
        public static string GETROOMCARD {
            get {
                return ResourceManager.GetString("GETROOMCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团购 的本地化字符串。
        /// </summary>
        public static string GROUPBUY {
            get {
                return ResourceManager.GetString("GROUPBUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请保持此界面，并联系管理员！ 的本地化字符串。
        /// </summary>
        public static string HOLDANDCALLADMIN {
            get {
                return ResourceManager.GetString("HOLDANDCALLADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请将身份证放在读卡区域！ 的本地化字符串。
        /// </summary>
        public static string IDCARD_MSG {
            get {
                return ResourceManager.GetString("IDCARD_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证模块故障 的本地化字符串。
        /// </summary>
        public static string IDCARDDEVICEFAULT {
            get {
                return ResourceManager.GetString("IDCARDDEVICEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证已过有效期，不能入住！ 的本地化字符串。
        /// </summary>
        public static string IDCARDOVERDUE {
            get {
                return ResourceManager.GetString("IDCARDOVERDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入钞模块故障：请联系前台人员。点击“确定”按钮，请重试，“取消”返回主界面\n 的本地化字符串。
        /// </summary>
        public static string INMONEYERROR {
            get {
                return ResourceManager.GetString("INMONEYERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入钞完成。 的本地化字符串。
        /// </summary>
        public static string INMONEYOK {
            get {
                return ResourceManager.GetString("INMONEYOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的手机号！输入完成请点击下一步！ 的本地化字符串。
        /// </summary>
        public static string INPUTPHONE {
            get {
                return ResourceManager.GetString("INPUTPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的验证码和手机号！输入完成请点击下一步！ 的本地化字符串。
        /// </summary>
        public static string INPUTVILIDATIONCODE {
            get {
                return ResourceManager.GetString("INPUTVILIDATIONCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请将房卡插入房卡出入口！ 的本地化字符串。
        /// </summary>
        public static string INSERTROOMCARD {
            get {
                return ResourceManager.GetString("INSERTROOMCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卡出错 的本地化字符串。
        /// </summary>
        public static string INSERTROOMCARDERROR {
            get {
                return ResourceManager.GetString("INSERTROOMCARDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机出现故障，请前往前台办理！ 的本地化字符串。
        /// </summary>
        public static string MACHINE_ERROR {
            get {
                return ResourceManager.GetString("MACHINE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件故障，请重试。 的本地化字符串。
        /// </summary>
        public static string MACHINE_ERROR_RETRY {
            get {
                return ResourceManager.GetString("MACHINE_ERROR_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额不足，请联系前台。 的本地化字符串。
        /// </summary>
        public static string MONEYNOTENOUGH {
            get {
                return ResourceManager.GetString("MONEYNOTENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络通讯错误,请保持本界面状态,联系前台相关人员。\n点击“确认”后将返回主界面。 的本地化字符串。
        /// </summary>
        public static string NETCOMMUNICATION {
            get {
                return ResourceManager.GetString("NETCOMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络通讯错误。 的本地化字符串。
        /// </summary>
        public static string NETCOMMUNICATIONERROR {
            get {
                return ResourceManager.GetString("NETCOMMUNICATIONERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在出卡。 的本地化字符串。
        /// </summary>
        public static string OUTCARD {
            get {
                return ResourceManager.GetString("OUTCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空。 的本地化字符串。
        /// </summary>
        public static string PASSWORDNULL {
            get {
                return ResourceManager.GetString("PASSWORDNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不正确，请重新输入。 的本地化字符串。
        /// </summary>
        public static string PASSWORDWORRY {
            get {
                return ResourceManager.GetString("PASSWORDWORRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号不能为空 的本地化字符串。
        /// </summary>
        public static string PHONENULL {
            get {
                return ResourceManager.GetString("PHONENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号长度必须为11位 的本地化字符串。
        /// </summary>
        public static string PHONENUMBERLENGTH {
            get {
                return ResourceManager.GetString("PHONENUMBERLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请将身份证放在身份证读卡区域！ 的本地化字符串。
        /// </summary>
        public static string PLACEIDCARD {
            get {
                return ResourceManager.GetString("PLACEIDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印出错。 的本地化字符串。
        /// </summary>
        public static string PRINTERROR {
            get {
                return ResourceManager.GetString("PRINTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在打印... 的本地化字符串。
        /// </summary>
        public static string PRINTING {
            get {
                return ResourceManager.GetString("PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印完成，请取凭条。 的本地化字符串。
        /// </summary>
        public static string PRINTOK {
            get {
                return ResourceManager.GetString("PRINTOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请交押金、房费{0}元! 的本地化字符串。
        /// </summary>
        public static string PUTINMONEY {
            get {
                return ResourceManager.GetString("PUTINMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在重试... 的本地化字符串。
        /// </summary>
        public static string RETRYING {
            get {
                return ResourceManager.GetString("RETRYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在为您制作房卡！请稍后！ 的本地化字符串。
        /// </summary>
        public static string ROOMCARDFABRICATION {
            get {
                return ResourceManager.GetString("ROOMCARDFABRICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不能为空 的本地化字符串。
        /// </summary>
        public static string VALIDATIONNULL {
            get {
                return ResourceManager.GetString("VALIDATIONNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请交押金、房费{0}元! 的本地化字符串。
        /// </summary>
        public static string WAITINMONEY {
            get {
                return ResourceManager.GetString("WAITINMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好！很高兴为您服务！ 的本地化字符串。
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string WRAN {
            get {
                return ResourceManager.GetString("WRAN", resourceCulture);
            }
        }
    }
}
